config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'pages#home'
  get 'docs', to: 'pages#docs'
  get 'marketing', to: 'pages#marketing'
  get 'references', to: 'pages#references'
  get 'articles', to: 'pages#articles'
  get 'training', to: 'pages#training'
  get 'answers', to: 'pages#answers'
  get 'email-sequences', to: 'pages#email-sequences'
  get 'invite-webinar', to: 'pages#invite-webinar'
  get 'steps-to-sale', to: 'pages#steps-to-sale'
  get 'training-vids', to: 'pages#training-vids'
  get 'lead-generation', to: 'pages#lead-generation'
  get 'lead-generation-faq', to: 'pages#lead-generation-faq'
  
  match '/users',     to: 'users#index',  via: 'get'
  match '/users/:id', to: 'users#show',   via: 'get'

  resources :users

  devise_for :users, :controllers => { registrations: 'registrations' }, :path_prefix => 'd'
  resources :prospects do
    resources :comments
  end
  root 'pages#home'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :prospect
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_prospect, only: [:create, :edit, :update, :destroy]
	before_action :find_comment, only: [:edit, :update, :destroy]
  
	def create
		# creates a comment with respect to the prospect
		@comment = @prospect.comments.create(comment_params)
		@comment.user_id = current_user.id

		if @comment.save
			redirect_to prospect_path(@prospect)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @comment.update(comment_params)
			redirect_to prospect_path(@prospect)
		else
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		redirect_to prospect_path(@prospect)
	end

	private

		def comment_params
			params.require(:comment).permit(:content)
		end

		def find_prospect
			@prospect = Prospect.find(params[:prospect_id])
		end

		def find_comment
			@comment = @prospect.comments.find(params[:id])
		end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
	<p><%= comment.content %></p>
	<p class="comment-posted-by">Posted by <%= comment.user.advisor_first_name + ' ' + comment.user.advisor_last_name %> <%= time_ago_in_words(comment.created_at) %> ago</p>

	<div class="links">
		<% if comment.user_id == current_user.id %>
			<%= link_to "Edit", edit_prospect_comment_path(comment.prospect, comment) %>| &nbsp; 
			<%= link_to "Delete", prospect_comment_path(comment.prospect, comment), method: :delete, data: { confirm: "Are you sure?" } %>
		<% end %>
	</div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@prospect, @prospect.comments.build]) do |f| %>
	<%= f.input :content, label: "Add Comment" %>
	<%= f.button :submit, :class => 'btn btn-kontrol' %>
<% end %>

app/views/comments/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="prospect-show">
		<h3>Edit Comment</h3>
		<%= simple_form_for([@prospect, @comment]) do |f| %>
			<%= f.input :content, label: "Comment" %>
			<%= f.button :submit, :class => 'btn btn-kontrol' %>
		<% end %>
	</div>
</div>