config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'pages#home'
  get 'docs', to: 'pages#docs'
  get 'marketing', to: 'pages#marketing'
  get 'references', to: 'pages#references'
  get 'articles', to: 'pages#articles'
  get 'training', to: 'pages#training'
  get 'answers', to: 'pages#answers'
  get 'email-sequences', to: 'pages#email-sequences'
  get 'invite-webinar', to: 'pages#invite-webinar'
  get 'steps-to-sale', to: 'pages#steps-to-sale'
  get 'training-vids', to: 'pages#training-vids'
  get 'lead-generation', to: 'pages#lead-generation'
  get 'lead-generation-faq', to: 'pages#lead-generation-faq'
  
  match '/users',     to: 'users#index',  via: 'get'
  match '/users/:id', to: 'users#show',   via: 'get'

  resources :users

  devise_for :users, :controllers => { registrations: 'registrations' }, :path_prefix => 'd'
  resources :prospects do
    resources :comments
  end
  root 'pages#home'
end

app/models/prospect.rb
class Prospect < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :delete_all
  validates :organization, :presence => true




  def self.to_csv
    attributes = %w{advisor_first_name advisor_last_name organization street_address address2 city state zip phone website employees revenue vc_already prospect_note intro_presentation_date estimated_ap sm_presentation_date actual_ap sm_conversion_est conversion_percentage status agreement_date sm_received_date sm_status contact1_first_name contact1_last_name contact1_title contact1_phone contact1_mobile contact1_email contact2_first_name contact2_last_name contact2_title contact2_phone contact2_mobile contact2_email primary_contact intro_presenter sm_presenter close_date references_given}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |prospect|
        csv << prospect.attributes.values_at(*attributes)
      end
    end
  end



  
  def self.search(query)
    # Note that PostgreSQL is case specific for like when searching where sqlite3 is not
    where("LOWER(organization) like ?", "%#{query.downcase}%")
    # To search by more than one variable, do the following
    # where("LOWER(organization) like ? OR LOWER(status) like ?", "%#{query.downcase}%", "%#{query.downcase}%")
  end
  
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  before_action :find_prospect, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  def index
    if params[:status] == nil

      if params[:search]
        @prospects = Prospect.search(params[:search]).order("created_at DESC")
      else
        @prospects = Prospect.all.order('user_id DESC')
        
        # respond_to do |format|
        #   format.html
        #   format.csv { send_data @prospects.to_csv, filename: "Prospects-#{Date.today}.csv" }
        # end
        
      end

    else
      @prospects = Prospect.where(status: params[:status])
    end
    @status = Prospect.select(:status).order(:status).distinct
  end
  
  def show
  end
  
  def new
    @prospect = current_user.prospects.build
  end
  
  def create
    @prospect = current_user.prospects.build(prospect_params)
    if @prospect.save
      flash[:success] = "New prospect added."
      redirect_to prospects_path
    else
      render 'new'
    end
  end

  def edit
  end
  
  def update
    if @prospect.update(prospect_params)
      flash[:success] = "Prospect has been updated."
      redirect_to prospect_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @prospect.destroy
    flash[:danger] = "Prospect has been deleted."
    redirect_to root_path
  end

  private
    def prospect_params
      params.require(:prospect).permit(:organization, :street_address, :address2, :city, :state, :zip, :phone, :website, :employees, :revenue, :vc_already, :prospect_note, :intro_presentation_date, :estimated_ap, :sm_presentation_date, :actual_ap, :sm_conversion_est, :conversion_percentage, :status, :agreement_date, :sm_received_date, :sm_status, :contact1_first_name, :contact1_last_name, :contact1_title, :contact1_phone, :contact1_mobile, :contact1_email, :contact2_first_name, :contact2_last_name, :contact2_title, :contact2_phone, :contact2_mobile, :contact2_email, :primary_contact, :intro_presenter, :sm_presenter, :close_date, :references_given)
    end

    def find_prospect
      @prospect = Prospect.find(params[:id])
    end

end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/views/prospects/_form.html.erb
<%= simple_form_for @prospect do |f| %>
	<%= f.input :organization, label: "Organization Name" %>
	<%= f.input :street_address %>
	<%= f.input :address2 %>
	<%= f.input :city %>
	<%= f.input :state %>
	<%= f.input :zip %>
	<%= f.input :phone %>
	<%= f.input :website %>
	<%= f.input :employees %>
	<%= f.input :revenue %>
	<%= f.input :vc_already, label: 'VC Now?' %>
	<%= f.input :prospect_note %>
	<%= f.input :intro_presentation_date, {:include_blank => true, :default => nil, order: [:day, :month, :year] } %>
	<%= f.input :estimated_ap %>
	<%= f.input :sm_presentation_date, {:include_blank => true, :default => nil, order: [:day, :month, :year] } %>
	<%= f.input :sm_status %>
	<%= f.input :actual_ap %>
	<%= f.input :sm_conversion_est %>
	<%= f.input :conversion_percentage %>
	<%= f.input :status %>
	<%= f.input :agreement_date, {:include_blank => true, :default => nil, order: [:day, :month, :year] } %>
	<%= f.button :submit %>
<% end %>

app/views/prospects/edit.html.erb
<div class="col-md-4 col-md-offset-4">
	<div class="prospect-show">
    <h3>Edit Prospect</h3>
    <br>
		<%= simple_form_for @prospect do |f| %>
			<%= f.input :organization, label: "Organization Name" %>
			<%= f.input :street_address %> 
      <%= f.input :address2 %> 
      <%= f.input :city %> 
			<%= f.input :state, collection: [
																	      ['Alabama', 'AL'],
																	      ['Alaska', 'AK'],
																	      ['Arizona', 'AZ'],
																	      ['Arkansas', 'AR'],
																	      ['California', 'CA'],
																	      ['Colorado', 'CO'],
																	      ['Connecticut', 'CT'],
																	      ['Delaware', 'DE'],
																	      ['District of Columbia', 'DC'],
																	      ['Florida', 'FL'],
																	      ['Georgia', 'GA'],
																	      ['Hawaii', 'HI'],
																	      ['Idaho', 'ID'],
																	      ['Illinois', 'IL'],
																	      ['Indiana', 'IN'],
																	      ['Iowa', 'IA'],
																	      ['Kansas', 'KS'],
																	      ['Kentucky', 'KY'],
																	      ['Louisiana', 'LA'],
																	      ['Maine', 'ME'],
																	      ['Maryland', 'MD'],
																	      ['Massachusetts', 'MA'],
																	      ['Michigan', 'MI'],
																	      ['Minnesota', 'MN'],
																	      ['Mississippi', 'MS'],
																	      ['Missouri', 'MO'],
																	      ['Montana', 'MT'],
																	      ['Nebraska', 'NE'],
																	      ['Nevada', 'NV'],
																	      ['New Hampshire', 'NH'],
																	      ['New Jersey', 'NJ'],
																	      ['New Mexico', 'NM'],
																	      ['New York', 'NY'],
																	      ['North Carolina', 'NC'],
																	      ['North Dakota', 'ND'],
																	      ['Ohio', 'OH'],
																	      ['Oklahoma', 'OK'],
																	      ['Oregon', 'OR'],
																	      ['Pennsylvania', 'PA'],
																	      ['Puerto Rico', 'PR'],
																	      ['Rhode Island', 'RI'],
																	      ['South Carolina', 'SC'],
																	      ['South Dakota', 'SD'],
																	      ['Tennessee', 'TN'],
																	      ['Texas', 'TX'],
																	      ['Utah', 'UT'],
																	      ['Vermont', 'VT'],
																	      ['Virginia', 'VA'],
																	      ['Washington', 'WA'],
																	      ['West Virginia', 'WV'],
																	      ['Wisconsin', 'WI'],
																	      ['Wyoming', 'WY']
																	    ] %>
			<%= f.input :zip %> 
			<%= f.input :phone, label: "Organization Phone" %>
			<%= f.input :website %>
			<%= f.input :employees, label: "# of Employees" %> 
      <%= f.input :revenue, label: "Annual Revenue" %>
			<hr>
			<h4>Contact 1</h4>
			<%= f.input :contact1_first_name, label: "First Name" %>
			<%= f.input :contact1_last_name, label: "Last Name" %>
			<%= f.input :contact1_title, label: "Title" %>
			<%= f.input :contact1_phone, label: "Direct Phone or Ext" %>
			<%= f.input :contact1_mobile, label: "Mobile" %>
			<%= f.input :contact1_email, label: "Email" %>
			<br>
			<h4>Contact 2</h4>
			<%= f.input :contact2_first_name, label: "First Name" %>
			<%= f.input :contact2_last_name, label: "Last Name" %>
			<%= f.input :contact2_title, label: "Title" %>
			<%= f.input :contact2_phone, label: "Direct Phone or Ext" %>
			<%= f.input :contact2_mobile, label: "Mobile" %>
			<%= f.input :contact2_email, label: "Email" %>
			<hr>
			<%= f.input :intro_presentation_date, {:include_blank => true, :default => nil, order: [:day, :month, :year] } %>
			<%= f.input :intro_presenter, label: "Intro Presentation (who presented?)" %>
			<%= f.input :estimated_ap, label: "Estimated Annual AP (include all digits)" %>
			
      <%= f.input :sm_received_date, {:include_blank => true, :default => nil, order: [:day, :month, :year], label: "Supplier Match Data Received Date" } %>
      <%= f.input :actual_ap, label: "Actual Annual AP (include all digits)" %>
      <%= f.input :vc_already, label: "Using VC for AP Already" %>
      <%= f.input :sm_conversion_est, label: "SM Conversion Est (include all digits)" %>
      <%= f.input :sm_presentation_date, {:include_blank => true, :default => nil, order: [:day, :month, :year], label: "Supplier Match Presentation Date" } %>
			<%= f.input :sm_presenter, label: "Supplier Match Presenter (who presented?)" %>
			<%= f.input :prospect_note, label: "Note" %>
			<%= f.input :status, collection: [
																				'Scheduling Team Presentation',
																				'Team Presentation Scheduled',
																				'Waiting for NDA',
																				'Waiting for Supplier Data',
																				'Waiting for Supplier Match',
																				'Scheduling SM / Demo',
																				'SM / Demo Scheduled',
																				'Waiting on Agreement',
																				'Closed - Agreement Received',
																				'Intro Pres Given - No Sale',
																				'SM Demo Given - No Sale',
																				'Not Qualified'
																				], label: "Deal Status" %>
      <%= f.input :close_date, {:label => "Kickoff Call or Proposed Close Date", :include_blank => true, :default => nil, order: [:day, :month, :year] } %>
			<%= f.input :references_given, as: :boolean, label: "References Given" %>
      <%= f.input :agreement_date, {:include_blank => true, :default => nil, order: [:day, :month, :year] } %>
      <br>
      
  			<%= link_to "Back", prospect_path, class: "btn btn-default" %>
        <%= f.button :submit, class:"btn btn-kontrol" %>
      
		<% end %>
	</div>
</div>

app/views/prospects/index.html.erb
<% est_ap = 0 %>
<% act_ap = 0 %>
<% sm_conv = 0 %>

<div class="col-md-12">
	<center>
		<%= form_tag(prospects_path, :method => "get", id: "search-form") do %>
			<%= text_field_tag :search, params[:search], placeholder: "Search Prospects" %>
			<%= submit_tag "Search", class:"btn btn-kontrol" %>
		<% end %>
	</center>
	<br>

	<div class="prospect-show table-responsive">
		
		<h3>Listing
			<% if current_user.manager %>
 				<%= @prospects.count %>
			<% else %>
				All
			<% end %>
		Prospects</h3>
		
		<table class="table index-table table-condensed">
		  <thead>
		    <tr>
		      <th>Consultant</th>
		      <th>Prospect</th>
		      <th>Intro<br>Presentation</th>
					<th>Days Since<br>Intro Pres</th>
		      <th>Estimated<br>Annual AP</th>
		      <th>Actual AP</th>
		      <th>SM Conversion<br>$ Estimate</th>
		      <th>%<br>Converted</th>
		      <th>SM & Demo<br>Presentation</th>
		      <th>Days Since<br>SM Pres</th>
		      <th>Deal 
		      	<div class="status">
			      	<li class="dropdown">
							  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Status <span class="caret"></span></a>
							  <ul class="dropdown-menu status-menu" style="list-style: none;">
							    <li><%= link_to "All", prospects_path %></li>
							    <% @status.each do |a| %>
							      <li class="black"><%= link_to "#{a.status}", prospects_path(status: a.status) %></li>
							    <% end %>
							  </ul>
							</li>
						</div>
					</th>
		      <th>Agreement<br>Date</th>
		    </tr>
		  </thead>
			
		  <tbody class="bordered">
				<% @prospects.each do |prospect| %>
					<% if (prospect.user_id == current_user.id) || current_user.manager %>
				    <tr>
				      <td class="td-left"><%= prospect.user.advisor_first_name + ' ' + prospect.user.advisor_last_name %></td>
				      <td class="td-left"><strong><%= link_to prospect.organization, prospect %></strong></td>
				      <td><% if !prospect.intro_presentation_date.nil? %>
				      		<%= prospect.intro_presentation_date.strftime("%m/%d/%Y") %>
				      		<% end %></td>
				      <td><% if !prospect.intro_presentation_date.nil? && (prospect.intro_presentation_date < Date.today) %>
              		<%= (Date.today - prospect.intro_presentation_date).to_i %> days
				      		<% end %></td>
				      <td><%= number_to_currency(prospect.estimated_ap, precision: 0) %></td>
				      <td><%= number_to_currency(prospect.actual_ap, precision: 0) %></td>
				      <td><%= number_to_currency(prospect.sm_conversion_est, precision: 0) %></td>
				      <td><% if (prospect.sm_conversion_est / prospect.actual_ap) > 0.00001 %>
				      		<%= number_to_percentage((prospect.sm_conversion_est / prospect.actual_ap)*100, precision: 1) %>
				      		<% end %></td>
				      <td><% if !prospect.sm_presentation_date.nil? %>
				      		<%= prospect.sm_presentation_date.strftime("%m/%d/%Y") %>
				      		<% end %></td>
				      		
				      <td><% if !prospect.sm_presentation_date.nil? && (prospect.sm_presentation_date < Date.today) %>
              		<%= (Date.today - prospect.sm_presentation_date).to_i %> days
				      		<% end %></td>
				      		
				      <td><%= prospect.status %></td>
				      <td><% if !prospect.agreement_date.nil? %>
				      		<%= prospect.agreement_date.strftime("%m/%d/%Y") %>
				      		<% end %></td>
				    </tr>
					<% end %>
					<% est_ap = est_ap + prospect.estimated_ap %>
					<% act_ap = act_ap + prospect.actual_ap %>
					<% sm_conv = sm_conv + prospect.sm_conversion_est %>
				<% end %>
		  </tbody>
			<% if current_user.manager? %>
			  <tfoot>		  
					<tr>
						<td>Total</td>
						<td></td>
						<td></td>
						<td></td>
						<td><%= number_to_currency(est_ap, precision: 0) %></td>
						<td><%= number_to_currency(act_ap, precision: 0) %></td>
						<td><%= number_to_currency(sm_conv, precision: 0) %></td>
			      <td><% if sm_conv > 0 && act_ap > 0 %>
			      			<% if (sm_conv / act_ap) > 0.00001 %>
			      				<%= number_to_percentage((sm_conv / act_ap)*100, precision: 1) %>
			      			<% end %>
			      		<% end %></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
					</tr>
			  </tfoot>
			 <% end %>
		</table>
		<%= link_to "Add New Prospect", new_prospect_path, class: "btn btn-kontrol btn-lg" %>
	</div>
</div>

app/views/prospects/new.html.erb
<div class="col-md-4 col-md-offset-4">
	<div class="prospect-show">
		<h3 class="new-prospect-header">Add New Prospect</h3>
		<br>
		<p><strong><em>Please only enter prospects with whom you have already given an Overview Presentation.</em></strong></p>
		<br>
		
		<%= simple_form_for @prospect do |f| %>
			<%= f.input :organization, required: true, autofocus: true, label: "Organization Name" %> 
			<%= f.input :state, collection: [
																	      ['Alabama', 'AL'],
																	      ['Alaska', 'AK'],
																	      ['Arizona', 'AZ'],
																	      ['Arkansas', 'AR'],
																	      ['California', 'CA'],
																	      ['Colorado', 'CO'],
																	      ['Connecticut', 'CT'],
																	      ['Delaware', 'DE'],
																	      ['District of Columbia', 'DC'],
																	      ['Florida', 'FL'],
																	      ['Georgia', 'GA'],
																	      ['Hawaii', 'HI'],
																	      ['Idaho', 'ID'],
																	      ['Illinois', 'IL'],
																	      ['Indiana', 'IN'],
																	      ['Iowa', 'IA'],
																	      ['Kansas', 'KS'],
																	      ['Kentucky', 'KY'],
																	      ['Louisiana', 'LA'],
																	      ['Maine', 'ME'],
																	      ['Maryland', 'MD'],
																	      ['Massachusetts', 'MA'],
																	      ['Michigan', 'MI'],
																	      ['Minnesota', 'MN'],
																	      ['Mississippi', 'MS'],
																	      ['Missouri', 'MO'],
																	      ['Montana', 'MT'],
																	      ['Nebraska', 'NE'],
																	      ['Nevada', 'NV'],
																	      ['New Hampshire', 'NH'],
																	      ['New Jersey', 'NJ'],
																	      ['New Mexico', 'NM'],
																	      ['New York', 'NY'],
																	      ['North Carolina', 'NC'],
																	      ['North Dakota', 'ND'],
																	      ['Ohio', 'OH'],
																	      ['Oklahoma', 'OK'],
																	      ['Oregon', 'OR'],
																	      ['Pennsylvania', 'PA'],
																	      ['Puerto Rico', 'PR'],
																	      ['Rhode Island', 'RI'],
																	      ['South Carolina', 'SC'],
																	      ['South Dakota', 'SD'],
																	      ['Tennessee', 'TN'],
																	      ['Texas', 'TX'],
																	      ['Utah', 'UT'],
																	      ['Vermont', 'VT'],
																	      ['Virginia', 'VA'],
																	      ['Washington', 'WA'],
																	      ['West Virginia', 'WV'],
																	      ['Wisconsin', 'WI'],
																	      ['Wyoming', 'WY']
																	    ] %>
			<%= f.input :phone, label: "Organization Phone" %>
			<%= f.input :website %>
			<hr>
			<%= f.input :contact1_first_name, label: "First Name" %>
			<%= f.input :contact1_last_name, label: "Last Name" %>
			<%= f.input :contact1_title, label: "Title" %>
			<%= f.input :contact1_phone, label: "Direct Phone or Ext" %>
			<%= f.input :contact1_mobile, label: "Mobile" %>
			<%= f.input :contact1_email, label: "Email" %>
			<hr>
			<%= f.input :intro_presentation_date, {:include_blank => true, :default => nil, order: [:day, :month, :year] } %>
			<%= f.input :intro_presenter, label: "Intro Presentation (who presented?)" %>
			<%= f.input :estimated_ap %>
			<%= f.input :prospect_note, label: "Note" %>
			<%= f.input :status, collection: [
																				'Scheduling Team Presentation',
																				'Team Presentation Scheduled',
																				'Waiting for NDA',
																				'Waiting for Supplier Data',
																				'Waiting for Supplier Match',
																				'Scheduling SM / Demo',
																				'SM / Demo Scheduled',
																				'Waiting on Agreement',
																				'Closed - Agreement Received',
																				'Intro Pres Given - No Sale',
																				'SM Demo Given - No Sale',
																				'Not Qualified'
																				], label: "Deal Status" %>
			<br>
			<%= link_to "Back", prospects_path, class: "btn btn-default" %>
			<%= f.button :submit, class:"btn btn-kontrol" %>
		<% end %>
	</div>
</div>

app/views/prospects/show.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="prospect-show">
		<h3><%= @prospect.organization %></h3>
		<br>
		<p class="prospect-posted-by">Posted by <%= @prospect.user.advisor_first_name + ' ' +
		@prospect.user.advisor_last_name %> <%= time_ago_in_words(@prospect.created_at) %> ago  
		and last updated <%= time_ago_in_words(@prospect.updated_at) %> ago.</p>
		
		<p>
		  <% if @prospect.status == "Intro Presentation Conducted" ||
		        @prospect.status == "SM / Demo Conducted" ||
		        @prospect.status == "No Sale" %>
		    <div class="alert alert-danger"><strong>IMPORTANT MESSAGE:</strong><br>
		    <em>Please update the status of this prospect. "<strong><%= @prospect.status  %></strong>" is no longer a valid status.</em></div>
		  <% end %>
		</p>
		
		<table align="center">
		  <tr>
		    <td width="350" valign="top">
		      <%= @prospect.street_address %><% if !@prospect.address2.nil? %>, <%= @prospect.address2 %><% end %><br>
        	<%= @prospect.city %>, <%= @prospect.state %> <%= @prospect.zip %><br>
        	<%= @prospect.phone %><br>
        	<%= @prospect.website %><br>
        	Employees: <%= @prospect.employees %><br>
			    Annual Revenue: <%= number_to_currency(@prospect.revenue, precision: 0) %><br>
        	Using VC for AP Now? <% if @prospect.vc_already == true %> Yes <% else %> No <% end %>
		    </td>
		    
		    <td width="100">&nbsp;</td>
		    
		    <td width="350" valign="top">
		      <% if !@prospect.contact1_first_name.nil? %>
          <%= @prospect.contact1_first_name %> <%= @prospect.contact1_last_name %><br>
          Title: <%= @prospect.contact1_title %><br>
          Phone: <%= @prospect.contact1_phone %><br>
          Mobile: <%= @prospect.contact1_mobile %><br>
          <%= @prospect.contact1_email %><br>
          <% end %>
          <br>
		      <% if !@prospect.contact2_first_name.nil? %>
          <%= @prospect.contact2_first_name %> <%= @prospect.contact2_last_name %><br>
          Title: <%= @prospect.contact2_title %><br>
          Phone: <%= @prospect.contact2_phone %><br>
          Mobile: <%= @prospect.contact2_mobile %><br>
          Email: <%= @prospect.contact2_email %><br>
          <% end %>
		    </td>
		  </tr>
		</table>
		
		<table>
		  <tr>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td>Other: <%= @prospect.prospect_note %></td>
		  </tr>
		  <tr>
		    <td>&nbsp;</td>
		  </tr>
		  
		</table>
  	
  	<table>
  	  <tr>
  	    <td width="350" valign="top">
  	      Intro Pres Date: <% if !@prospect.intro_presentation_date.nil? %>
				  <%= @prospect.intro_presentation_date.strftime("%m/%d/%Y") %><% end %><br>
				  Intro Presented by: <%= @prospect.intro_presenter %><br>
			    Est Annual AP: <%= number_to_currency(@prospect.estimated_ap, precision: 0) %><br>
  	      SM Data Received Date: <% if !@prospect.sm_received_date.nil? %>
				  <%= @prospect.sm_received_date.strftime("%m/%d/%Y") %><% end %>
  	    </td>
  	     
  	     <td width="100"></td>
  	     
  	    <td width="350" valign="top">
          Actual Annual AP: <%= number_to_currency(@prospect.actual_ap, precision: 0) %><br>
          SM Conversion Est: <%= number_to_currency(@prospect.sm_conversion_est, precision: 0) %><br>
          Conversion Percentage: <% if (@prospect.sm_conversion_est / @prospect.actual_ap) > 0.00001 %>
  		    <%= number_to_percentage((@prospect.sm_conversion_est / @prospect.actual_ap)*100, precision: 1) %><% end %><br>    
  	       
        </td>
  	  </tr>
  	</table>
    <p>&nbsp;</p>
  	<table>
  	  <tr>
  	    <td width="350" valign="top">
  	      SM Pres Date: <% if !@prospect.sm_presentation_date.nil? %>
				  <%= @prospect.sm_presentation_date.strftime("%m/%d/%Y") %><% end %><br>
				  SM Presented by: <%= @prospect.sm_presenter %><br>
  	    </td>
  	     
        <td width="100"></td>
  	     
  	    <td width="350" valign="top">
  	      Proposed Close Date/<br>
  	      Kickoff Call Date: <% if !@prospect.close_date.nil? %>
				  <%= @prospect.close_date.strftime("%m/%d/%Y") %><% end %>
  	      Agreement Date: <% if !@prospect.agreement_date.nil? %>
				  <%= @prospect.agreement_date.strftime("%m/%d/%Y") %><% end %>	
  	     </td>
        </td>
  	  </tr>
  	</table>
  	
		<table>
		  <tr>
		    <td>References Provided: 
		      <% if @prospect.references_given == true %>
	          YES
	        <% else %>
	          NO
	        <% end %> 
        </td>
		  </tr>
		  <tr>
		    <td>&nbsp;</td>
		  </tr>
		  <tr>
		    <td><h4>Status: <%= @prospect.status %></h4></td>
		  </tr>
		  <tr>
		    <td>&nbsp;</td>
		  </tr>
		</table>

		<hr>

		<p><%= render @prospect.comments %></p>

		<%= render 'comments/form' %>

    <br>
			<%= link_to "Back", prospects_path, class: "btn btn-default" %>
			<%= link_to "Edit & More Fields", edit_prospect_path(@prospect), class: "btn btn-warning" %>
			<%= link_to "Delete", prospect_path(@prospect), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>

	</div>
</div>