config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'pages#home'
  get 'docs', to: 'pages#docs'
  get 'marketing', to: 'pages#marketing'
  get 'references', to: 'pages#references'
  get 'articles', to: 'pages#articles'
  get 'training', to: 'pages#training'
  get 'answers', to: 'pages#answers'
  get 'email-sequences', to: 'pages#email-sequences'
  get 'invite-webinar', to: 'pages#invite-webinar'
  get 'steps-to-sale', to: 'pages#steps-to-sale'
  get 'training-vids', to: 'pages#training-vids'
  get 'lead-generation', to: 'pages#lead-generation'
  get 'lead-generation-faq', to: 'pages#lead-generation-faq'
  
  match '/users',     to: 'users#index',  via: 'get'
  match '/users/:id', to: 'users#show',   via: 'get'

  resources :users

  devise_for :users, :controllers => { registrations: 'registrations' }, :path_prefix => 'd'
  resources :prospects do
    resources :comments
  end
  root 'pages#home'
end

app/views/layouts/_footer.html.erb
  <nav class="navbar navbar-default navbar-fixed-bottom">
      <p align="center" style="color:gray;"><br>&copy; 2018</p>
  </nav>

app/views/layouts/_head.html.erb
  <head>
    <title>Kontrol - Accounts Payable Payment Solutions</title>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Chris Cunningham">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" %>
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" %>    
    <%= csrf_meta_tags %>
  </head>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%#= link_to image_tag("kontrol-logo.png", alt: "logo"), '/', class: 'navbar-brand' %>
        </div>
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
    				<% if user_signed_in? %>
              <li><%= link_to root_path do %><i class="fa fa-home"></i> Home<% end %></li>
              <% if current_user.manager || current_user.support %>
    					  <li><%= link_to users_path do %><i class="fa fa-users"></i> Users<% end %></li>
              <% end %>
              <li><%= link_to prospects_path do %><i class="fa fa-crosshairs"></i> Prospects<% end %></li>
    					<li><%= link_to edit_user_registration_path do %><i class="fa fa-gear"></i> <%= current_user.advisor_first_name + ' ' + current_user.advisor_last_name %><% end %></li>
    					<li><%= link_to destroy_user_session_path, method: :delete do %><i class="fa fa-lock"></i> Sign out<% end %></li>
    					<!--<li> <%#= image_tag avatar_url(current_user, 50) %></li>-->
    				<% else %>
    					<li><%= link_to new_registration_path(resource_name) do %><i class="fa fa-user-plus"></i> Sign up<% end %></li> 
    					<li><%= link_to new_user_session_path do %><i class="fa fa-unlock"></i> Log in<% end %></li>    					
    				<% end %>
          </ul>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!-- Author Chris Cunningham January 28th 2018 -->

<!DOCTYPE html>
<html>

	<%= render 'layouts/head' %>
  
  <body>

		<%= render 'layouts/nav' %>

    <div class="container-fluid">

      <%= render 'layouts/messages' %>       

    	<%= yield %>
    </div>
 
	  <%#= render 'layouts/footer' %>
	  
  </body>
  
</html>